config/routes.rb
Rails.application.routes.draw do

  devise_for :members
  resources :profiles

  match 'members/dashboard' => 'members#dashboard', :via => :get

  scope :members do
    root :to => 'members#dashboard', as: :member_root
  end

  get 'members/dashboard'

  root 'pages#index'

  get 'pages/about'

  get 'pages/services'

  get 'pages/contact'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!

  def dashboard
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :description, :email, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_footer.html.erb
<!-- FOOTER : begin -->
			<div id="footer" class="m-parallax">

				<% unless member_signed_in? %>
					<!-- FOOTER TOP : begin -->
					<div class="footer-top">
						<div class="footer-top-inner">
							<div class="container">

								
									<!-- CTA MESSAGE : begin -->
									<div class="c-cta-message m-has-button">
										<div class="cta-inner">
											<h2>We Are <strong>Hiring</strong>!</h2>
											<p>The copy warned the Little Blind Text, that where it came from it would have been rewritten.</p>
											<p class="cta-button"><a href="contact.html" class="c-button m-size-medium">Contact Us</a></p>
										</div>
									</div>
									<!-- CTA MESSAGE : end -->
							</div>
						</div>
					</div>
					<!-- FOOTER TOP : end -->
				<% end %>

				<!-- FOOTER INNER : begin -->
				<div class="footer-inner">
					<div class="container">

						<!-- BOTTOM PANEL : begin -->
						<div id="bottom-panel">
							<div class="row">
								<div class="col-md-4">

									<!-- TEXT WIDGET : begin -->
									<div class="widget text-widget">
										<div class="widget-inner">
											<h3 class="widget-title">About <strong>Handyguyz</strong></h3>
											<div class="widget-content">
												<p><strong>Handyguyz</strong> was founded with the vision of <strong>being a catalyst</strong> in job creations for the <strong>blue collar</strong> sector. We want to reach out to families <strong>across America</strong>, helping to enrich, enhance and <strong>empower people</strong> from a variety <strong>of trades</strong>, helping them through <strong>networking</strong> within their industry.</p>

											</div>
										</div>
									</div>
									<!-- TEXT WIDGET : end -->

									<hr class="c-divider hidden-lg hidden-md">

								</div>
								<div class="col-md-4">

									<!-- TEXT WIDGET (CONTACT) : begin -->
									<div class="widget text-widget">
										<div class="widget-inner">
											<h3 class="widget-title">Quick <strong>Contact</strong></h3>
											<div class="widget-content">

												<p>Please call <strong>(123) 456 789</strong> (we are available 24/7) or write at <strong><a href="#">help@handyguyz.com</a></strong>.</p>
												<p><strong>Handyguyz Inc.</strong><br>
												123 Fake Street<br>
												V5R 7RB, Vancouver BC</p>

											</div>
										</div>
									</div>
									<!-- TEXT WIDGET (CONTACT) : end -->

									<hr class="c-divider hidden-lg hidden-md">

								</div>
								<div class="col-md-4">

									<!-- SUBSCRIBE WIDGET : begin -->
									<div class="widget subscribe-widget">
										<div class="widget-inner">
											<h3 class="widget-title">Join Our <strong>Newsletter</strong></h3>
											<div class="widget-content">

												<p>We hate spam. We will only send you important information, and only when we <strong>have</strong> something to say</p>

												<form class="subscribe-widget-form" action="#" method="get">

													<!-- VALIDATION ERROR MESSAGE : begin -->
													<p style="display: none;" class="c-alert-message m-warning m-validation-error"><i class="ico fa fa-exclamation-circle"></i>Email address is required.</p>
													<!-- VALIDATION ERROR MESSAGE : end -->

													<!-- SENDING REQUEST ERROR MESSAGE : begin -->
													<p style="display: none;" class="c-alert-message m-warning m-request-error"><i class="ico fa fa-exclamation-circle"></i>There was a connection problem. Try again later.</p>
													<!-- SENDING REQUEST ERROR MESSAGE : end -->

													<!-- SUCCESS MESSAGE : begin -->
													<p style="display: none;" class="c-alert-message m-success"><i class="ico fa fa-check-circle"></i><strong>Sent successfully.</strong></p>
													<!-- SUCCESS MESSAGE : end -->

													<div class="input-box">
														<input class="email-input m-required m-email" name="EMAIL" type="text" placeholder="Your email address here" title="Your email address here">
														<button class="submit-btn" type="submit" title="Subscribe"><i class="fa fa-chevron-right"></i></button>
													</div>

												</form>

											</div>
										</div>
									</div>
									<!-- SUBSCRIBE WIDGET : end -->

								</div>
							</div>
						</div>
						<!-- BOTTOM PANEL : end -->

						<div class="row">
							<div class="col-md-6 col-md-push-6">

								<!-- FOOTER MENU : begin -->
								<nav class="footer-menu">
									<ul>
										<li><%= link_to 'Register as Handyguy', '#' %></li>
										<li><%= link_to 'Post a Job', '#' %></li>
									</ul>
								</nav>
								<!-- FOOTER MENU : end -->

							</div>
							<div class="col-md-6 col-md-pull-6">

								<!-- FOOTER TEXT : begin -->
								<div class="footer-text">
									<p>Created with <i class="fa fa-heart" style="color: red;"></i> in Canada.</p>
								</div>
								<!-- FOOTER TEXT : end -->

							</div>
						</div>

					</div>
				</div>
				<!-- FOOTER INNER : end -->

			</div>
			<!-- FOOTER : end -->

app/views/layouts/_nav.html.erb
<!-- HEADER : begin -->
			<header id="header">
				<div class="header-inner">
					<div class="container">

						<!-- HEADER BRANDING : begin -->
						<div class="header-branding">
							<div class="branding-inner">

								<!-- BRANDING LOGO : begin -->
								<div class="brading-logo">
									<%= link_to root_path do %>
										<%= image_tag "logo.png" %>
									<% end %>
								</div>
								<!-- BRANDING LOGO : end -->

								<!-- BRANDING INFO : begin -->
								<div class="brading-info">
									<strong>Handyguyz</strong><br>
									<em>Handyman Network</em>
								</div>
								<!-- BRANDING INFO : end -->

							</div>
						</div>
						<!-- HEADER BRANDING : end -->

						<!-- NAVIGATION TOGGLE : begin -->
						<button class="header-navigation-toggle" type="button"><i class="fa fa-bars"></i></button>
						<!-- NAVIGATION TOGGLE : end -->

						<!-- HEADER NAVIGATION : begin -->
						<div class="header-navigation">
							<div class="navigation-inner">

								<!-- HEADER MENU : begin -->
								<nav class="header-menu">
									<ul>
										<li>
											<%= link_to 'Home', root_path %>
										</li>
										<li>
											<%= link_to 'Services', pages_services_path %>
										</li>
										<li><%= link_to 'About', pages_about_path %></li>	
										<li><%= link_to 'Contact', pages_contact_path %></li>
										<% if member_signed_in? %>
											<li>
												<%= link_to('Logout', destroy_member_session_path, :method => :delete) %>
											</li>
										<% else %>
											<li>
												<%= link_to 'Login', new_member_session_path %>
											</li>
										<% end %>
									</ul>
								</nav>
								<!-- HEADER MENU : end -->
							</div>
						</div>
						<!-- HEADER NAVIGATION : end -->

					</div>
				</div>
			</header>
			<!-- HEADER : end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HandyV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- GOOGLE FONTS : begin -->
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic%7cExo+2:400,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <!-- GOOGLE FONTS : end -->

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

</head>
<body class="m-fixed-header">
<div id="wrapper">
	<%= render 'layouts/nav' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

	<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/members/dashboard.html.erb
<!-- CORE : begin -->
			<div id="core">

				<!-- PAGE TITLE : begin -->
				<div id="page-title" class="m-parallax">

					<!-- PAGE TITLE TOP : begin -->
					<div class="page-title-top">
						<div class="page-title-top-inner">

							<!-- PAGE TITLE TEXT : begin -->
							<div class="page-title-text">
								<div class="container">
									<h1>Dashboard</h1>
								</div>
							</div>
							<!-- PAGE TITLE TEXT : end -->

						</div>
					</div>
					<!-- PAGE TITLE TOP : end -->

					<!-- PAGE TITLE BOTTOM : begin -->
					<div class="page-title-bottom">
						<div class="container">
							<div class="page-title-bottom-inner">
								<div class="page-title-bottom-inner2">

									<!-- PAGE TITLE BREADCRUMBS : begin -->
									<div class="page-title-breadcrumbs">
										<!--<ul>
											<li><a href="index.html">Home</a></li>
											<li>About Us</li>
										</ul>-->
									</div>
									<!-- PAGE TITLE BREADCRUMBS : end -->

								</div>
							</div>
						</div>
					</div>
					<!-- PAGE TITLE BOTTOM : end -->

				</div>
				<!-- PAGE TITLE : end -->

				<div class="container">

					<!-- PAGE CONTENT : begin -->
					<div id="page-content">

						<h2>Welcome to your <strong>Handyguyz </strong>dashboard.</h2>
						<p>Here you can find all the tools required for you to be succesfull on our platform. <br>Here, you can create your<strong> profile</strong>, upload a<strong> portfolio</strong> or bid on customers <strong>job posts</strong>.
						</p>
						<br>
						<p>
							<%= link_to "EDIT PROFILE", profiles_path, class: "c-button m-type-2 m-size-large" %>
						</p>

						<hr class="c-divider m-size-medium">

						<h2>Current <strong>Portfolio</strong></h2>

						<div class="row">
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-01.jpg" alt="">
									</div>
									<h3 class="member-name">John Handy</h3>
									<h4 class="member-role">Plumbing, Sanitary, Sewerage</h4>
									<div class="member-description">
										<p>The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

								<hr class="c-divider m-transparent hidden-md hidden-lg">

							</div>
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-02.jpg" alt="">
									</div>
									<h3 class="member-name">Keith Skilful</h3>
									<h4 class="member-role">Heating, Electricity</h4>
									<div class="member-description">
										<p>Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

								<hr class="c-divider m-transparent hidden-md hidden-lg">

							</div>
						</div>

						<hr class="c-divider m-size-small m-transparent">

						<div class="row">
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-03.jpg" alt="">
									</div>
									<h3 class="member-name">Mick Nifty</h3>
									<h4 class="member-role">Roofing, Renovation</h4>
									<div class="member-description">
										<p>But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

								<hr class="c-divider m-transparent hidden-md hidden-lg">

							</div>
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-04.jpg" alt="">
									</div>
									<h3 class="member-name">Joe Slick</h3>
									<h4 class="member-role">Painting, Electricity</h4>
									<div class="member-description">
										<p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

							</div>
						</div>

					</div>
					<!-- PAGE CONTENT : end -->

				</div>

			</div>
			<!-- CORE : end -->

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already have account?", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Register", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/pages/about.html.erb
<!-- CORE : begin -->
			<div id="core">

				<!-- PAGE TITLE : begin -->
				<div id="page-title" class="m-parallax">

					<!-- PAGE TITLE TOP : begin -->
					<div class="page-title-top">
						<div class="page-title-top-inner">

							<!-- PAGE TITLE TEXT : begin -->
							<div class="page-title-text">
								<div class="container">
									<h1>About Us</h1>
								</div>
							</div>
							<!-- PAGE TITLE TEXT : end -->

						</div>
					</div>
					<!-- PAGE TITLE TOP : end -->

					<!-- PAGE TITLE BOTTOM : begin -->
					<div class="page-title-bottom">
						<div class="container">
							<div class="page-title-bottom-inner">
								<div class="page-title-bottom-inner2">

									<!-- PAGE TITLE BREADCRUMBS : begin -->
									<div class="page-title-breadcrumbs">
										<!--<ul>
											<li><a href="index.html">Home</a></li>
											<li>About Us</li>
										</ul>-->
									</div>
									<!-- PAGE TITLE BREADCRUMBS : end -->

								</div>
							</div>
						</div>
					</div>
					<!-- PAGE TITLE BOTTOM : end -->

				</div>
				<!-- PAGE TITLE : end -->

				<div class="container">

					<!-- PAGE CONTENT : begin -->
					<div id="page-content">

						<h2>We have <strong>25 Years of Experience</strong><br>in Home Maintenance Business</h2>
						<p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown </p>

						<hr class="c-divider m-size-medium">

						<h2>Our <strong>Team</strong></h2>

						<div class="row">
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-01.jpg" alt="">
									</div>
									<h3 class="member-name">John Handy</h3>
									<h4 class="member-role">Plumbing, Sanitary, Sewerage</h4>
									<div class="member-description">
										<p>The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

								<hr class="c-divider m-transparent hidden-md hidden-lg">

							</div>
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-02.jpg" alt="">
									</div>
									<h3 class="member-name">Keith Skilful</h3>
									<h4 class="member-role">Heating, Electricity</h4>
									<div class="member-description">
										<p>Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

								<hr class="c-divider m-transparent hidden-md hidden-lg">

							</div>
						</div>

						<hr class="c-divider m-size-small m-transparent">

						<div class="row">
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-03.jpg" alt="">
									</div>
									<h3 class="member-name">Mick Nifty</h3>
									<h4 class="member-role">Roofing, Renovation</h4>
									<div class="member-description">
										<p>But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

								<hr class="c-divider m-transparent hidden-md hidden-lg">

							</div>
							<div class="col-md-6">

								<!-- TEAM MEMBER : begin -->
								<div class="c-team-member m-has-portrait">
									<div class="member-portrait">
										<img src="/assets/team-member-04.jpg" alt="">
									</div>
									<h3 class="member-name">Joe Slick</h3>
									<h4 class="member-role">Painting, Electricity</h4>
									<div class="member-description">
										<p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts.</p>
									</div>
									<!--<ul class="member-social">
										<li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
									</ul>-->
								</div>
								<!-- TEAM MEMBER : end -->

							</div>
						</div>

					</div>
					<!-- PAGE CONTENT : end -->

				</div>

			</div>
			<!-- CORE : end -->

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<!-- CORE : begin -->
      <div id="core">

        <!-- PAGE TITLE : begin -->
        <div id="page-title" class="m-parallax">

          <!-- PAGE TITLE TOP : begin -->
          <div class="page-title-top">
            <div class="page-title-top-inner">

              <!-- PAGE TITLE TEXT : begin -->
              <div class="page-title-text">
                <div class="container">
                  <h1>Edit Your Profile</h1>
                </div>
              </div>
              <!-- PAGE TITLE TEXT : end -->

            </div>
          </div>
          <!-- PAGE TITLE TOP : end -->
      </div>

      <div class="container">

          <!-- PAGE CONTENT : begin -->
          <div id="page-content">

			<%= render 'form' %>

			<%= link_to 'Show', @profile %> |
			<%= link_to 'Back', profiles_path %>
		  </div>
	  </div>
	 </div>

app/views/profiles/index.html.erb
<!-- CORE : begin -->
      <div id="core">

        <!-- PAGE TITLE : begin -->
        <div id="page-title" class="m-parallax">

          <!-- PAGE TITLE TOP : begin -->
          <div class="page-title-top">
            <div class="page-title-top-inner">

              <!-- PAGE TITLE TEXT : begin -->
              <div class="page-title-text">
                <div class="container">
                  <h1>My Profile</h1>
                </div>
              </div>
              <!-- PAGE TITLE TEXT : end -->

            </div>
          </div>
          <!-- PAGE TITLE TOP : end -->
      </div>

      <div class="container">

          <!-- PAGE CONTENT : begin -->
          <div id="page-content">
            <hr class="c-divider m-transparent">
            <p id="notice"><%= notice %></p>

            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Email</th>
                  <th>Address</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @profiles.each do |profile| %>
                  <tr>
                    <td><%= profile.name %></td>
                    <td><%= profile.description %></td>
                    <td><%= profile.email %></td>
                    <td><%= profile.address %></td>
                    <td><%= link_to 'Show', profile %></td>
                    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
                    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= link_to 'New Profile', new_profile_path %> | <%= link_to 'Back to Dashboard', members_dashboard_path %>
</div>
</div>
</div>

app/views/profiles/new.html.erb
<!-- CORE : begin -->
      <div id="core">

        <!-- PAGE TITLE : begin -->
        <div id="page-title" class="m-parallax">

          <!-- PAGE TITLE TOP : begin -->
          <div class="page-title-top">
            <div class="page-title-top-inner">

              <!-- PAGE TITLE TEXT : begin -->
              <div class="page-title-text">
                <div class="container">
                  <h1>Edit Your Profile</h1>
                </div>
              </div>
              <!-- PAGE TITLE TEXT : end -->

            </div>
          </div>
          <!-- PAGE TITLE TOP : end -->
      </div>

      <div class="container">

          <!-- PAGE CONTENT : begin -->
          <div id="page-content">

			<%= render 'form' %>

		  </div>

			<%= link_to 'Back', profiles_path %>
</div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @profile.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>